# Generated by Django 4.1.5 on 2023-01-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name_plural': 'Doctors'},
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='doctors',
            name='last_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
