# Generated by Django 4.1.5 on 2023-01-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine', '0004_alter_doctors_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='current_token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='tokens',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
