# Generated by Django 4.1.5 on 2023-01-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine', '0005_doctors_current_token_doctors_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
