# Generated by Django 4.1.5 on 2023-01-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine', '0006_doctors_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='current_token',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='tokens',
            field=models.CharField(blank=True, default='0', max_length=300),
        ),
    ]
