# Generated by Django 4.1.5 on 2023-01-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine', '0007_alter_doctors_current_token_alter_doctors_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='next_token',
            field=models.CharField(blank=True, default='waiting for update', max_length=10),
        ),
    ]
