# Generated by Django 4.1.5 on 2023-01-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine', '0008_doctors_next_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='confirm',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='current_token',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='next_token',
            field=models.CharField(default='waiting for update', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='tokens',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
