# Generated by Django 4.1.5 on 2023-01-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine', '0009_remove_doctors_confirm_alter_doctors_current_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='current_token',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='next_token',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='tokens',
            field=models.CharField(default='', max_length=300),
        ),
    ]
